logging:
  file: ssmlserver.log
  level:
    org.springframework.dsl: debug
    org.springframework.statemachine.dsl: debug
spring:
  main:
    banner-mode: "off"
  dsl:
    lsp:
      server:
        mode: PROCESS
