logging:
  file: ssmlserver.log
  level:
    org.springframework.dsl: info
spring:
  main:
    banner-mode: "off"
  dsl:
    lsp:
      server:
        mode: PROCESS
        force-jvm-exit-on-shutdown: false
